name: Build Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
    - name: Install Dependencies
      run: |
        sudo apt update && \
        sudo apt install -y libgtk-4-dev clang
    - name: Build
      run: swift build -v
    #- name: Run tests
      #run: swift test -v
